config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from . import views


app_name = 'pybo'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('laws_data/', views.laws_data, name='laws_data'),
    path('regulation_data/', views.regulation_data, name='regulation_data'),
    path('SKTL_policy_data/', views.SKTL_policy_data, name='SKTL_policy_data'),
    path('guide_data/', views.guide_data, name='guide_data'),
    path('trend_data/', views.trend_data, name='trend_data'),
    path('magazine_data/', views.magazine_data, name='magazine_data'),
    path('', views.index, name='index'),
    path('laws/<int:laws_id>/', views.laws_detail, name='laws_detail'),
    path('regulation_detail/<int:regulation_id>/', views.regulation_detail, name='regulation_detail'),
    path('SKTL_policy_detail/<int:SKTL_policy_id>/', views.SKTL_policy_detail, name='SKTL_policy_detail'),
    path('guide_detail/<int:guide_id>/', views.guide_detail, name='guide_detail'),
    path('trend_detail/<int:trend_id>/', views.trend_detail, name='trend_detail'),
    path('magazine_detail/<int:magazine_id>/', views.magazine_detail, name='magazine_detail'),
    path('question/<int:question_id>/', views.detail, name='detail'),
    path('laws_answer/create/<int:laws_id>/', views.laws_answer_create, name='laws_answer_create'),
    path('regulation_answer/create/<int:regulation_id>/', views.regulation_answer_create, name='regulation_answer_create'),
    path('SKTL_policy_answer/create/<int:SKTL_policy_id>/', views.SKTL_policy_answer_create, name='SKTL_policy_answer_create'),
    path('guide_answer/create/<int:guide_id>/', views.guide_answer_create, name='guide_answer_create'),
    path('trend_answer/create/<int:trend_id>/', views.trend_answer_create, name='trend_answer_create'),
    path('magazine_answer/create/<int:magazine_id>/', views.magazine_answer_create, name='magazine_answer_create'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('fileupload/', views.fileUpload, name='fileupload'),
    path('laws/create', views.laws_create, name='laws_create'),
    path('regulation/create', views.regulation_create, name='regulation_create'),
    path('SKTL_policy/create', views.SKTL_policy_create, name='SKTL_policy_create'),
    path('guide/create', views.guide_create, name='guide_create'),
    path('trend/create', views.trend_create, name='trend_create'),
    path('magazine/create', views.magazine_create, name='magazine_create'),
    path('download/<int:pk>', views.laws_download_view, name="laws_download"),
    path('download/<int:pk>', views.regulation_download_view, name="regulation_download"),
    path('download/<int:pk>', views.SKTL_policy_download_view, name="SKTL_policy_download"),
    path('download/<int:pk>', views.guide_download_view, name="guide_download"),
    path('download/<int:pk>', views.trend_download_view, name="trend_download"),
    path('download/<int:pk>', views.magazine_download_view, name="magazine_download"),

    #<int: >안에 들어가는 변수명은 view 에서 받는 함수의 () 인자명과 일치해야해
    #answer_create 가 views.answer_create 를 호출하고 <int:quesiton_id>를 넘깁니다.
    #view.answer_create 함수에는 "def answer_create(request, question_id):" 와 같이 () 안의 인자명과 일치해야함
]

pybo/models.py
from django.db import models
from uuid import uuid4
from datetime import datetime
# Create your models here

def get_file_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    return '/'.join(['upload_file/', ymd_path, uuid_name])

class Model_laws_data(models.Model):
    subject = models.CharField(max_length=200)
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    imgfile = models.ImageField(null=True, upload_to=get_file_path, blank=True, verbose_name='이미지')  # Need to do "pip3 install image" in cmd
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Model_regulation(models.Model):
    subject = models.CharField(max_length=200)
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Model_SKTL_policy(models.Model):
    subject = models.CharField(max_length=200)
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Model_guide(models.Model):
    subject = models.CharField(max_length=200)
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Model_trend(models.Model):
    subject = models.CharField(max_length=200)
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Model_magazine(models.Model):
    image = models.ImageField(upload_to='images/', blank=True, null=True, default='images/no_img.jpg')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    # modify_date = models.DateTimeField(null=True, blank=True)

class FileUpload(models.Model):
    title = models.TextField(max_length=40, null=True)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    content = models.TextField()

    def __str__(self):
        return self.title

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    imgfile = models.ImageField(null=True, upload_to="", blank=True)  # Need to do "pip3 install image" in cmd, upload_to 는 저장될경로로 ""는 media 폴더를 의미
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject






class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class laws_Answer(models.Model):
    laws_data = models.ForeignKey(Model_laws_data, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class regulation_Answer(models.Model):
    regulation = models.ForeignKey(Model_regulation, null=True, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class SKTL_policy_Answer(models.Model):
    SKTL_policy = models.ForeignKey(Model_SKTL_policy, null=True, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class guide_Answer(models.Model):
    guide = models.ForeignKey(Model_guide, null=True, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class trend_Answer(models.Model):
    trend = models.ForeignKey(Model_trend, null=True, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class magazine_Answer(models.Model):
    magazine = models.ForeignKey(Question, null=True, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, FileUpload, Model_laws_data, laws_Answer, Model_regulation, regulation_Answer, Model_SKTL_policy, SKTL_policy_Answer, Model_guide, guide_Answer, Model_trend, trend_Answer, Model_magazine, magazine_Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content', 'imgfile']
        labels = {
            'subject':'제목',
            'content':'내용',
            'imgfile':'첨부파일',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

# form 은 fomrs.Form 을 상속받으면 폼, forms.ModelForm을 상속받으면 모델 폼이라 부른다. 
# 여기서는 form.ModelForm 을 상속받음. 모델 폼은 말 그대로 모델과 연결된 폼이며, 모델폼 객체를 저장하면 연결된 모델의 데이터를 저장
# 즉 별도로 template 에서 DB에 접근하지 않아도 된다.
# Template(.html) - ModelForm - Model(DB) 와 같이 ModelForm 이 html 과 DB 를 연결

class laws_Form(forms.ModelForm):
    class Meta:
        model = Model_laws_data
        fields = ['subject', 'content', 'upload_files']
        labels = {
            'subject':'제목',
            'content':'내용',
            'upload_files':'첨부파일',
        }

class laws_AnswerForm(forms.ModelForm):
    class Meta:
        model = laws_Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

class regulation_Form(forms.ModelForm):
    class Meta:
        model = Model_regulation
        fields = ['subject', 'content', 'upload_files']
        labels = {
            'subject':'제목',
            'content':'내용',
            'upload_files':'첨부파일',
        }

class regulation_AnswerForm(forms.ModelForm):
    class Meta:
        model = regulation_Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

class SKTL_policy_Form(forms.ModelForm):
    class Meta:
        model = Model_SKTL_policy
        fields = ['subject', 'content', 'upload_files']
        labels = {
            'subject':'제목',
            'content':'내용',
            'upload_files':'첨부파일',
        }

class SKTL_policy_AnswerForm(forms.ModelForm):
    class Meta:
        model = SKTL_policy_Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

class guide_Form(forms.ModelForm):
    class Meta:
        model = Model_guide
        fields = ['subject', 'content', 'upload_files']
        labels = {
            'subject':'제목',
            'content':'내용',
            'upload_files':'첨부파일',
        }

class guide_AnswerForm(forms.ModelForm):
    class Meta:
        model = guide_Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

class trend_Form(forms.ModelForm):
    class Meta:
        model = Model_trend
        fields = ['subject', 'content', 'upload_files']
        labels = {
            'subject':'제목',
            'content':'내용',
            'upload_files':'첨부파일',
        }

class trend_AnswerForm(forms.ModelForm):
    class Meta:
        model = trend_Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

class magazine_Form(forms.ModelForm):
    class Meta:
        model = Model_magazine  # 사용할 모델
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class magazine_AnswerForm(forms.ModelForm):
    class Meta:
        model = magazine_Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

class FileUploadForm(forms.ModelForm):
    class Meta:
        model = FileUpload
        fields = ['title', 'imgfile', 'content']

templates/pybo/GuideManual.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <h1 class="border-bottom py-2">가이드 & 메뉴얼</h1>
    <table  class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">
                    {{ question.subject }}
                </a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colsapn="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary" >
        질문 등록하기
    </a>
</div>
{% endblock %}

<!--
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}
-->

templates/pybo/SKTL_policy_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ SKTL_policy_detail.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ SKTL_policy_detail.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ SKTL_policy_detail.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ SKTL_policy_detail.SKTL_policy_answer_set.count }}개의 답변이 있습니다.
    </h5>
    {% for answer in SKTL_policy_detail.SKTL_policy_answer_set.all %}
    <!-- SKTL_policy_detail.[MODEL명]_set.all -->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:SKTL_policy_answer_create' SKTL_policy_detail.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        {% if SKTL_policy_detail.upload_files %}
        <div class="col-12 text-right">
            <span>첨부파일 :&nbsp;&nbsp</span>
            <a href="{% url 'pybo:SKTL_policy_download' SKTL_policy_detail.id %}" >{{ SKTL_policy_detail.filename|truncatechars:25 }}</a>
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>

</div>
{% endblock %}

templates/pybo/SKTL_policy_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <h1 class="border-bottom py-2">SK텔링크 정책</h1>
    <table  class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if SKTL_policy_list %}
        {% for SKTL_policy in SKTL_policy_list %}
        <tr>
            <td>{{ SKTL_policy_list.paginator.count|sub:SKTL_policy_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
                <a href="{% url 'pybo:SKTL_policy_detail' SKTL_policy.id %}">
                    {{ SKTL_policy.subject }}
                </a>
            </td>
            <td>{{ SKTL_policy.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colsapn="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:SKTL_policy_create' %}" class="btn btn-primary" >
        질문 등록하기
    </a>
</div>
{% endblock %}

<!--
{% if SKTL_policy_list %}
    <ul>
    {% for SKTL_policy in SKTL_policy_list %}
        <li><a href="{% url 'pybo:detail' SKTL_policy.id %}">{{ SKTL_policy.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}
-->

templates/pybo/fileupload.html
{% extends 'base.html' %}
{% load static %}
{$ load bootstrap %}
{% block content %}
<div class="container">
    <form method="POST" action="{% url 'pybo:fileupload' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- views.py 에서 context 를 통해 전달되는 form 의 객체명은 하단에 작성 }} -->
        <!-- Q.실제 template 안의 구성은 아래 form 에서 가져오는건데... '파일선택' 버튼이라던지 이런건 어디서 가져오는거지...? -->
        <!-- A.form.as_p 를 하게 되면, html 구성요소를 자동으로 생성한다. 그러나 수동으로 별도로 생성할 수도 있다. 참고 : 자동(fileupload.html), 수동(question_form.html) -->
        {{ fileuploadForm.as_p }}
        <input type="submit" class="btn btn-primary col-12" value="제출">
    </form>
</div>
{% endblock %}

templates/pybo/home_backup.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <h1 class="border-bottom py-2">HOME</h1>
    <a href="../laws_data">법령자료</a><br>
    <a href="../regulation_data">지침자료</a><br>
    <a href="../SKTL_policy_data">SK텔링크정책</a><br>
    <a href="../guide_data">가이드 및 메뉴얼</a><br>
    <a href="../trend_data">최신동향</a><br>
</div>
{% endblock %}

<!--
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}
-->

templates/pybo/laws_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div id="inner">
        <div class="container my-3">
        <h1 class="border-bottom py-2">법령 자료</h1>
        <table  class="table">
            <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if laws_list %}
            {% for laws in laws_list %}
            <tr>
                <td>{{ laws_list.paginator.count|sub:laws_list.start_index|sub:forloop.counter0|add:1 }}</td>
                <td>
                    <a href="{% url 'pybo:laws_detail' laws.id %}">
                        {{ laws.subject }}
                        {% if laws.laws_answer_set.count > 0 %} <!-- '모델명_set' 이 네이밍 규칙 -->
                        <span class="text-danger small ml-2">
                            {{ laws.laws_answer_set.count }}
                        </span>
                        {% endif %}
                    </a>
                </td>
                <td>{{ laws.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colsapn="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <!-- 페이징 처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전 페이지 -->
            <!-- 이전 페이지가 있다면 '이전'링크가 활성화, 없으면 '이전'링크 비활성화 -->
            {% if laws_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ laws_list.previous_page_number }}"><!-- view.py의 page_obj -> {{ laws_list }} -->
                    이전
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" ara-disabled="true" href="#">
                    이전
                </a>
            </li>
            {% endif %}
            <!-- 페이지 리스트 -->
            <!-- for~endfor 페이지리스트를 돌면서 해당 페이지로 이동할 수 있는 링크 생성 -->
            {% for page_number in laws_list.paginator.page_range %}
            <!-- 현재 페이지(laws_list.number) 기준으로 좌우 5개씩 보이도록 -->
            <!-- A|add:-5 란 A에서 5만큼 빼라는 의미 -->
            {% if page_number >= laws_list.number|add:-5 and page_number <= laws_list.number|add:5 %}
                {% if page_number == laws_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">
                        {{ page_number }}
                    </a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">
                        {{ page_number }}
                    </a>
                </li>
                {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음 페이지 -->
            {% if laws_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ laws_list.next_page_number }}">
                    다음
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                    다음
                </a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징 처리 끝 -->
        <a href="{% url 'pybo:laws_create' %}" class="btn btn-primary" >
            질문 등록하기
        </a>
    </div>
    <div class="right_side"></div>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <table  class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <!-- 일련번호 = 전체 게시물 개수 - 시작 인덱스 - 현재 인덱스 + 1 -->
            <!-- question_list.paginator.count은 전체 게시물 개수, question_list.start_index은 시작인덱스(1부터), forloop.counter0은 0부터 시작 -->
            <!-- |add:5 는 +5를 의미, |sub:3은 -3을 의미 -->
            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">
                    {{ question.subject }}
                    {% if question.answer_set.count > 0 %}
                    <span class="text-danger small ml-2">
                        {{ question.answer_set.count }}
                    </span>
                    {% endif %}
                </a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colsapn="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        <!-- 이전 페이지가 있다면 '이전'링크가 활성화, 없으면 '이전'링크 비활성화 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ quesiton_list.previous_page_number }}"><!-- view.py의 page_obj -> {{ quesiton_list }} -->
                이전
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" ara-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        <!-- for~endfor 페이지리스트를 돌면서 해당 페이지로 이동할 수 있는 링크 생성 -->
        {% for page_number in question_list.paginator.page_range %}
        <!-- 현재 페이지(question_list.number) 기준으로 좌우 5개씩 보이도록 -->
        <!-- A|add:-5 란 A에서 5만큼 빼라는 의미 -->
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">
                다음
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary" >
        질문 등록하기
    </a>
</div>
{% endblock %}

<!--
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}
-->

templates/pybo/trend_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ trend_detail.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ trend_detail.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ trend_detail.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ trend_detail.trend_answer_set.count }}개의 답변이 있습니다.
    </h5>
    {% for answer in trend_detail.trend_answer_set.all %}
    <!-- trend_detail.[MODEL명]_set.all -->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:trend_answer_create' trend_detail.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        {% if trend_detail.upload_files %}
        <div class="col-12 text-right">
            <span>첨부파일 :&nbsp;&nbsp</span>
            <a href="{% url 'pybo:trend_download' trend_detail.id %}" >{{ trend_detail.filename|truncatechars:25 }}</a>
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>

</div>
{% endblock %}