config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from . import views


app_name = 'pybo'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('laws_data/', views.laws_data, name='laws_data'),
    path('regulation_data/', views.regulation_data, name='regulation_data'),
    path('SKTL_policy_data/', views.SKTL_policy_data, name='SKTL_policy_data'),
    path('guide_data/', views.guide_data, name='guide_data'),
    path('trend_data/', views.trend_data, name='trend_data'),
    path('magazine_data/', views.magazine_data, name='magazine_data'),
    path('', views.index, name='index'),
    path('laws/<int:laws_id>/', views.laws_detail, name='laws_detail'),
    path('regulation_detail/<int:regulation_id>/', views.regulation_detail, name='regulation_detail'),
    path('SKTL_policy_detail/<int:SKTL_policy_id>/', views.SKTL_policy_detail, name='SKTL_policy_detail'),
    path('guide_detail/<int:guide_id>/', views.guide_detail, name='guide_detail'),
    path('trend_detail/<int:trend_id>/', views.trend_detail, name='trend_detail'),
    path('magazine_detail/<int:magazine_id>/', views.magazine_detail, name='magazine_detail'),
    path('question/<int:question_id>/', views.detail, name='detail'),
    path('laws_answer/create/<int:laws_id>/', views.laws_answer_create, name='laws_answer_create'),
    path('regulation_answer/create/<int:regulation_id>/', views.regulation_answer_create, name='regulation_answer_create'),
    path('SKTL_policy_answer/create/<int:SKTL_policy_id>/', views.SKTL_policy_answer_create, name='SKTL_policy_answer_create'),
    path('guide_answer/create/<int:guide_id>/', views.guide_answer_create, name='guide_answer_create'),
    path('trend_answer/create/<int:trend_id>/', views.trend_answer_create, name='trend_answer_create'),
    path('magazine_answer/create/<int:magazine_id>/', views.magazine_answer_create, name='magazine_answer_create'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('fileupload/', views.fileUpload, name='fileupload'),
    path('laws/create', views.laws_create, name='laws_create'),
    path('regulation/create', views.regulation_create, name='regulation_create'),
    path('SKTL_policy/create', views.SKTL_policy_create, name='SKTL_policy_create'),
    path('guide/create', views.guide_create, name='guide_create'),
    path('trend/create', views.trend_create, name='trend_create'),
    path('magazine/create', views.magazine_create, name='magazine_create'),
    path('download/<int:pk>', views.laws_download_view, name="laws_download"),
    path('download/<int:pk>', views.regulation_download_view, name="regulation_download"),
    path('download/<int:pk>', views.SKTL_policy_download_view, name="SKTL_policy_download"),
    path('download/<int:pk>', views.guide_download_view, name="guide_download"),
    path('download/<int:pk>', views.trend_download_view, name="trend_download"),
    path('download/<int:pk>', views.magazine_download_view, name="magazine_download"),

    #<int: >안에 들어가는 변수명은 view 에서 받는 함수의 () 인자명과 일치해야해
    #answer_create 가 views.answer_create 를 호출하고 <int:quesiton_id>를 넘깁니다.
    #view.answer_create 함수에는 "def answer_create(request, question_id):" 와 같이 () 안의 인자명과 일치해야함
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bottstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <!-- Bootstrap icons-->
    <link rel="stylesheet" href="{% static 'bootstrap-icons.css' %}">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>SK Telink Security Potal</title>
</head>

<body class="pt-5">
<!-- include 기능을 이용하여 html 삽입할 수 있다 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- Bootstrap core JS-->
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
<!-- Core theme JS-->
<script src="{% static 'scripts.js' %}"></script>
<!-- Footer-->
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; ICT Security Team</p></div>
</footer>

</body>
</html>

templates/base_backup.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- Bottstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <title>SK텔링크 보안포탈</title>
</head>
<body>
<!-- include 기능을 이용하여 html 삽입할 수 있다 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

</body>
</html>

templates/base_security_portal.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>수정's local</title>
</head>
<body>
{% include "security_portal/navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/navbar.html
<!-- 내비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container px-lg-0">
        <a class="navbar-brand" href="{% url 'pybo:home' %}">SKTL Security Potal</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    알림마당
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="#">공지사항</a></li>
                    <li><a class="dropdown-item" href="#">자주하는 질문응답</a></li>
                    <li><a class="dropdown-item" href="#">개인정보 바로알기</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    지원마당
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="#">방화벽 신청</a></li>
                    <li><a class="dropdown-item" href="#">IT지원요청서</a></li>
                    <li><a class="dropdown-item" href="#">보안 문의</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    자료마당
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="../laws_data">법령자료</a></li>
                    <li><a class="dropdown-item" href="../regulation_data">지침자료</a></li>
                    <li><a class="dropdown-item" href="../SKTL_policy_data">SK텔링크 정책</a></li>
                    <li><a class="dropdown-item" href="../guide_data">가이드 및 매뉴얼</a></li>
                    <li><a class="dropdown-item" href="../trend_data">최신동향</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    보안매거진
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="../magazine_data">뉴스클리핑</a></li>
                    <li><a class="dropdown-item" href="#">이달의 보안소식</a></li>
                    <li><a class="dropdown-item" href="#">알기쉬운 보안용어</a></li>
                    <li><a class="dropdown-item" href="#">개인정보보호 영상</a></li>
                  </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/navbar_backup.html
<!-- 내비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottm">
    <a class="navbar-brand" href="{% url 'pybo:home' %}">HOME</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="'navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="https://www.naver.com">Link-ON</a>
            </li>
        </ul>
    </div>
</nav>

<!-- 왼쪽 서브 네비게이션 바 메뉴
    <div id="wrapper">
        <div class="topbar" style="position: absolute; top:0;">
            <div class="left side-menu">
                <div class="sidebar-inner">
                    <div id="sidebar-menu">
                        <ul>
                            <li class="has_sub"><a href="javascript:void(0);" class="waves-effect">
                                <i class="fas fa-bars"></i>
                            </a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="left_sub_menu">
                <div class="sub_menu">
                    <input type="search" name="SEARCH" placeholder="SEARCH">
                    <h2>TITLE</h2>
                    <ul class="big_menu">
                        <li>MENU 1 <i class="arrow fas fa-angle-right"></i></li>
                        <ul class="small_menu">
                            <li><a href="#">소메뉴1-1</a></li>
                            <li><a href="#">소메뉴1-2</a></li>
                            <li><a href="">소메뉴1-3</a></li>
                            <li><a href="#">소메뉴1-4</a></li>
                        </ul>
                    </ul>
                    <ul class="big_menu">
                        <li>MENU 2 <i class="arrow fas fa-angle-right"></i></li>
                        <ul class="small_menu">
                            <li><a href="#">소메뉴2-1</a></li>
                            <li><a href="#"></a>소메뉴2-2</a></li>
                        </ul>
                    </ul>
                    <ul class="big_menu">
                        <li>MYPAGE</li>
                    </ul>
                </div>
            </div>
            <div class="overlay"></div>
        </div>
    </div>
-->

<!--
<nav>
    <ul class="menu">
        <li><a href="#html">HTML5</a></li>
        <li><a href="#html">CSS3</a></li>
    </ul>
</nav>
<style>
    nav{
        width:200px;
        background-color:#eee;
        boder-right:1px solid #ddd;
        position:fixed;
        height:100%
    }

    .menu {}
    .menu li {}

    .menu li a {
        height:40px;
        display:block;
        padding:10 20px;
        font-size:30px;
        color:#555;
    }
    .menu li a:hover { background-color:yellowgreen; color:white;}
</style>
-->